---
- name: "Generation du docker-compose file"
  template:
    src: "docker-compose-odoo.yml.j2"
    dest: /home/{{ ansible_user }}/docker-compose-odoo.yml
    mode: 0655
    force: false

- name: "DÃ©ploiement du docker-compose-odoo.yml"
  shell: "ls -l /home/{{ ansible_user }}/docker-compose-odoo.yml"
  register: command_output
- debug:
  var: command_output.stdout_lines
  #command: "docker-compose -f /home/{{ ansible_user }}/docker-compose-odoo.yml up -d"
